import React from 'react';
import { Button, Row, Col, Card, Alert, Stack } from 'react-bootstrap';
import { FileDown, Image as ImageIcon, FileText, Flag, Share2, Download } from 'lucide-react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { colors } from '../styles';

export function ActionButtons({ trustScore, contentId }) {
  
  // 1. Export Dashboard as PNG
  const exportAsImage = async (format = 'png') => {
    const element = document.getElementById('verify-section');
    if (!element) return;
    
    const canvas = await html2canvas(element, { 
      backgroundColor: colors.bg,
      scale: 2, // Higher quality
      useCORS: true 
    });
    
    const image = canvas.toDataURL(`image/${format}`);
    const link = document.createElement('a');
    link.href = image;
    link.download = `VeriTrust_Report_${contentId}.${format}`;
    link.click();
  };

  // 2. Export Professional PDF Certificate
  const exportAsPDF = () => {
    const doc = new jsPDF();
    
    // Background
    doc.setFillColor(19, 17, 17); 
    doc.rect(0, 0, 210, 297, 'F');
    
    // Header
    doc.setTextColor(43, 68, 255); 
    doc.setFontSize(26);
    doc.text('VeriTrust Forensic Report', 20, 40);
    
    // Content
    doc.setTextColor(248, 249, 250); 
    doc.setFontSize(14);
    doc.text(`Content ID: ${contentId}`, 20, 60);
    doc.text(`Authenticity Score: ${trustScore}%`, 20, 75);
    doc.text(`Analysis Date: ${new Date().toLocaleString()}`, 20, 90);
    doc.text(`Status: ${trustScore >= 70 ? 'VERIFIED AUTHENTIC' : 'HIGH RISK'}`, 20, 105);
    
    // Branding
    doc.setFontSize(10);
    doc.setTextColor(173, 181, 189);
    doc.text('Generated by Team CODRIX • C2PA Compliant Standard', 20, 280);
    
    doc.save(`VeriTrust_Certificate_${contentId}.pdf`);
  };

  const handleShare = () => {
    const shareText = `VeriTrust Analysis: This content has an Authenticity Score of ${trustScore}%. Verify your digital truth.`;
    navigator.clipboard.writeText(shareText);
    alert("Result copied to clipboard!");
  };

  return (
    <Card className="shadow-sm border-0 p-4 mt-5" style={{ backgroundColor: colors.bgCard, border: '1px solid rgba(255,255,255,0.15)' }}>
      <Card.Title className="h5 mb-4 text-white">Verification Actions</Card.Title>
      
      <Row className="g-3 mb-4">
        <Col md={4}>
          <Button 
            variant="danger"
            className="w-100 py-3 d-flex align-items-center justify-content-center gap-2 border-0 fw-bold"
            style={{ backgroundColor: colors.errorRed }}
            onClick={() => alert("Reported to Team CODRIX Admin.")}
          >
            <Flag size={20} /> Report Forgery
          </Button>
        </Col>

        <Col md={4}>
          <Button 
            variant="primary"
            className="w-100 py-3 d-flex align-items-center justify-content-center gap-2 border-0 fw-bold shadow-sm"
            onClick={exportAsPDF}
          >
            <Download size={20} /> Download PDF
          </Button>
        </Col>

        <Col md={4}>
          <Button 
            variant="success"
            className="w-100 py-3 d-flex align-items-center justify-content-center gap-2 border-0 fw-bold"
            onClick={handleShare}
          >
            <Share2 size={20} /> Share Result
          </Button>
        </Col>
      </Row>

      <Stack direction="horizontal" gap={3} className="justify-content-center border-top border-secondary pt-4">
        <Button variant="outline-light" className="rounded-pill px-4" onClick={() => exportAsImage('png')}>
          <ImageIcon size={18} className="me-2" /> Save Full Dashboard as PNG
        </Button>
      </Stack>

      <Alert className="mt-4 mb-0 border-0 text-center" style={{ backgroundColor: 'rgba(239, 68, 68, 0.05)', color: colors.mutedText }}>
        <p className="mb-0 small">
          <strong>Privacy Notice:</strong> Analysis is processed locally. No personal data is stored by Team CODRIX.
        </p>
      </Alert>
    </Card>
  );
}